### ISSUE TITLE
Case-Insensitive file names

### ISSUE THREAD

**Issue by nicholas-pfeifer** [HagenSR/byte_le_royale_2022_release#2]
Potential issue regarding the Visualizer.x86_64 and visualizer.x86_64 file names
![Filename issue](https://user-images.githubusercontent.com/35605537/151669584-6454707e-2cdc-46cd-a7e4-a10201473e17.png)

**Comment by nicholas-pfeifer** [comment]
Could be the cause of other visualizer issues

**Comment by erickbickler** [comment]
removed lower case visualizer in new release, use upper-case one
