### ISSUE TITLE
Issue with map generation

### ISSUE THREAD

**Issue by Brojaga** [HagenSR/byte_le_royale_2022_release#3]
When running the visualizer, the visualizer loads correctly but the console displays the following error. This is when running the unedited client, just the release repo (windows 11 python 3.8.10)
![image](https://user-images.githubusercontent.com/28816967/151669799-8edec6a6-cc44-4871-afe0-6a388ecb5cb2.png)
![image](https://user-images.githubusercontent.com/28816967/151669847-91b6be74-a6fa-489a-b702-176478285537.png)

**Comment by Brojaga** [comment]
Repeating this process with the updated client removed the money errror from the console, but I don't want to close the issue since that seems to be a generation bug.

**Comment by erickbickler** [comment]
Should be fixed, I believe this was purely a visualizer bug
