### ISSUE TITLE
BAK file generated by Notepad++ breaks launcher.pyz

### ISSUE THREAD

**Issue by nicholas-pfeifer** [HagenSR/byte_le_royale_2022_release#4]
Just wanted to make the developers aware that editing/saving a client file in Notepad++ generates a BAK file. The launcher will try to use the BAK file rather than the correct client file to run the game. Issue can be fixed by deleting the BAK file.

**Comment by erickbickler** [comment]
This is most likely because the launcher checks for files with the name client in them. You can rename the BAK file to avoid this if you can, but we won't be changing this behavior for this competition.
