### ISSUE TITLE
Stuck in wall

### ISSUE THREAD

**Issue by JeanVArdent** [HagenSR/byte_le_royale_2022_release#5]
See logs: 2 different instances
[logs (2).zip](https://github.com/HagenSR/byte_le_royale_2022_release/files/7964350/logs.2.zip)
[logs.zip](https://github.com/HagenSR/byte_le_royale_2022_release/files/7964351/logs.zip)

**Comment by HagenSR** [comment]
may be fixed by removing rotation from hitbox ( Removing bugs often involves removing features, because bugs are features)

**Comment by HagenSR** [comment]
should be fixed

**Comment by HagenSR** [comment]
should be fixed
