### ISSUE TITLE
Unknown Runtime Error

### ISSUE THREAD

**Issue by Shad0w-Dragon** [HagenSR/byte_le_royale_2022_release#6]
[logs.zip](https://github.com/HagenSR/byte_le_royale_2022_release/files/7964413/logs.zip)
![Screenshot (10)](https://user-images.githubusercontent.com/91845760/151674922-96eda15d-5e06-40c1-a945-eafd7cbbf899.png)

**Comment by HagenSR** [comment]
Erick said he helped you. closing
